### ISSUE TITLE
Unable to unlock COPILOT

### ISSUE THREAD

**Issue by aimarxjg** [vladyxd/enable-copilot#1]
WIN11 Professional edition, can not select the preview mode, only CAY and DEV can choose, use the modify registry or.BAT can not activate COPILOT, can only run through WIN+r Microsofts-edge ://? ux=copilot&tcp=1&source=taskbar to call the COPILOT sidebar
=================================
Trying to use the.reg file, also invalid after the June update....
Windows Registry Editor Version 5.00
[HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Copilot\BingChat]
"IsUserEligible"=dword:00000001

**Comment by vladyxd** [comment]
Hey there. I was able to reproduce the issue. From what it seems and what I have tested so far, the issue seems to be related to the region.
Here's what I noticed:
 - Upon switching regions from Romania to the US (and rebooting) and after a little update to my script, I was able to get the copilot in the sidebar as well.
  - For it to come in the taskbar, it needs to be enabled, and to be enabled it must show in the taskbar personalization, which surely doesn't, so in this case I can only point you to using ViveTool or making a shortcut for the run script.
  I am sorry that I cannot make this automatically, but I guess we can just wait it out until Microsoft releases it Worldwide.
  
  P.S. I am also updating the script in a second, you could give that a shot.

**Comment by aimarxjg** [comment]
I'm in a lockdown area. Thank you for your response🙂
